export const motivationalMessages = [
    'Congratulations on your victory! Ready to conquer more?',
    'Well done on your achievement! Can you beat your own record?',
    'You are a winner! Keep the winning streak going!',
    'Great job! How about another round to test your skills?',
    'Keep up the good work! More challenges await!',
    'Outstanding performance! Let\'s aim higher next time!',
    'You did it! Ready for the next challenge?',
    'Fantastic effort! Let\'s see what you can achieve next!',
    'Bravo! Your journey to success continues!',
    'Way to go! Are you up for another exciting game?',
    'Awesome victory! Time to set new goals!',
    'Incredible win! What\'s your next move?',
    'Superb job! Keep pushing your limits!',
    'Impressive achievement! Keep the momentum going!',
    'Fantastic win! The sky\'s the limit!',
    'Well deserved win! Ready for the next challenge?',
    'Amazing performance! Can you do even better?',
    'Spectacular victory! Let\'s aim for perfection!',
    'Exceptional effort! What\'s your next challenge?',
    'Phenomenal win! Keep rising to the top!',
    'Stellar performance! Your skills are unmatched!',
    'Outstanding achievement! The journey continues!',
    'Remarkable win! What\'s your strategy for the next game?',
    'Brilliant job! What\'s your secret to success?',
    'Excellent victory! Keep shining bright!',
    'Impressive work! Ready to prove yourself again?',
    'Outstanding success! How will you top this?',
    'Terrific win! Are you ready for more?',
    'Remarkable job! What\'s your next big goal?',
    'Great win! Your determination is inspiring!',
  ];

  export const consolationMessages = [
    'Better luck next time!',
    'Don\'t be discouraged. You\'ll get there!',
    'Keep going! Success is just around the corner.',
    'Every setback is a setup for a comeback.',
    'Stay positive and keep pushing forward.',
    'Learn from this experience and grow stronger.',
    'Keep your head up. Your time will come.',
    'Failure is a part of the journey to success.',
    'You\'re closer to your goal than you think.',
    'Stay resilient and keep chasing your dreams.',
    'Believe in yourself, even when it\'s tough.',
    'Keep trying. You\'re on the path to greatness.',
    'Take this as an opportunity to improve.',
    'Keep persevering. You\'re capable of amazing things.',
    'Focus on progress, not perfection.',
    'Keep moving forward, one step at a time.',
    'Stay motivated and keep pushing through challenges.',
    'You\'re stronger than this setback.',
    'Stay determined. Success is waiting for you.',
    'Don\'t let one defeat define you. Keep going!',
    'You\'re capable of bouncing back stronger.',
    'Challenges make you stronger. Keep going!',
    'Persevere. Your hard work will pay off.',
    'Stay focused on your goals and keep moving forward.',
    'Stay positive. Your breakthrough is coming.',
    'Stay patient. Good things are on their way.',
    'Keep your spirits up. You\'re on the right track.',
    'You\'ve got what it takes. Keep pushing forward.',
    'Stay strong. Your determination will lead to success.',
  ];
  

  export const congratulationMessages = [
    'You are a winner, {name}!',
    'Great job, {name}!',
    'Keep up the good work, {name}!',
    'Outstanding performance, {name}!',
    'You did it, {name}!',
    'Fantastic effort, {name}!',
    'Bravo, {name}!',
    'Way to go, {name}!',
    'You nailed it, {name}!',
    'Incredible work, {name}!',
    'Impressive, {name}!',
    'Superb job, {name}!',
    'Congratulations, {name}!',
    'Kudos, {name}!',
    'Excellent, {name}!',
    'Sensational, {name}!',
    'Magnificent, {name}!',
    'Exceptional, {name}!',
    'Well done, {name}!',
    'Champion effort, {name}!',
    'Awesome, {name}!',
    'Top-notch, {name}!',
    'Legendary, {name}!',
    'Legendary achievement, {name}!',
    'Unparalleled, {name}!',
    'Unrivaled, {name}!',
    'Awe-inspiring, {name}!',
  ];
  
  export const condolenceMessages = [
    'Better luck next time, {name}.',
    'Don\'t give up, {name}.',
    'It\'s just the beginning, {name}.',
    'Keep trying, {name}.',
    'Learn from this experience, {name}.',
    'Stay positive, {name}.',
    'You\'ll get them next time, {name}.',
    'Every failure is a stepping stone to success, {name}.',
    'Stay strong, {name}.',
    'You\'ve got this, {name}.',
    'Don\'t be discouraged, {name}.',
    'Keep going, {name}.',
    'You\'re capable of amazing things, {name}.',
    'Believe in yourself, {name}.',
    'You\'re on the path to greatness, {name}.',
    'Failure is temporary, {name}.',
    'Stay resilient, {name}.',
    'You\'re stronger than you think, {name}.',
    'Keep your head up, {name}.',
    'Focus on progress, {name}.',
    'You\'re capable of bouncing back, {name}.',
    'Stay motivated, {name}.',
    'Challenges make you stronger, {name}.',
    'Persevere, {name}.',
    'Stay determined, {name}.',
    'You\'ll overcome this setback, {name}.',
  ];
  
  // Replace {name} with the winner's name when displaying the message
  